name: Test

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
    name: Ruby ${{ matrix.ruby-version }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run Rubocop
      run: bundle exec rake rubocop
    - name: Run Unit Tests
      run: bundle exec rake spec

  integration:
    runs-on: ubuntu-latest
    name: Integration

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - name: Cache Image
      uses: jamesmortensen/cache-container-images-action@v1
      with:
        images: |
          docker://ghcr.io/gsi-hpc/ona-dev:latest
    - name: Run Integration Tests
      run: bundle exec rake integration
